### ISSUE TITLE
Only first page is imported

### ISSUE THREAD

**Issue by midenok** [FlatIO/experiment-groovepizza#23]
It doesn't import the whole groove, does it?

Click on "Specials" -> "TRAP", then try to import it.

https://apps.musedlab.org/groovepizza/?museid=SJwOIr91L&

**Comment by gierschv** [comment]
Hi there,

Indeed, it only imports the first section. I think the reason I did that is that instruments can change between the sections of the groove, and I didn't want to have too much complexity. That's probably something we can change if we consider we keep the same instruments like in your example.

**Comment by midenok** [comment]
I'd really benefit from the full notes. I'd like to print the full pattern but there is no any measures of export apart from this one. I can not imagine how page limitation makes it better. If you just did the full export like it works now it could be at least usable for the multipage patterns no matter did they change instruments or not.

**Comment by gierschv** [comment]
Implemented today :) Let me know if you have any feedback.

**Comment by midenok** [comment]
Great! I'll get back to that in a while.
